// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/nervina-labs/cota-nft-entries-syncer/internal/app"
	"github.com/nervina-labs/cota-nft-entries-syncer/internal/biz"
	"github.com/nervina-labs/cota-nft-entries-syncer/internal/config"
	"github.com/nervina-labs/cota-nft-entries-syncer/internal/data"
	"github.com/nervina-labs/cota-nft-entries-syncer/internal/logger"
	"github.com/nervina-labs/cota-nft-entries-syncer/internal/service"
)

// Injectors from wire.go:

func initApp(database *config.Database, ckbNode *config.CkbNode, loggerLogger *logger.Logger) (*app.App, func(), error) {
	dataData, cleanup, err := data.NewData(database, loggerLogger)
	if err != nil {
		return nil, nil, err
	}
	checkInfoRepo := data.NewCheckInfoRepo(dataData, loggerLogger)
	checkInfoUsecase := biz.NewCheckInfoUsecase(checkInfoRepo, loggerLogger)
	kvPairRepo := data.NewKvPairRepo(dataData, loggerLogger)
	syncKvPairUsecase := biz.NewSyncKvPairUsecase(kvPairRepo, loggerLogger)
	ckbNodeClient, err := data.NewCkbNodeClient(ckbNode, loggerLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	systemScripts := data.NewSystemScripts(ckbNodeClient, loggerLogger)
	claimedCotaNftKvPairRepo := data.NewClaimedCotaNftKvPairRepo(dataData, loggerLogger)
	claimedCotaNftKvPairUsecase := biz.NewClaimedCotaNftKvPairUsecase(claimedCotaNftKvPairRepo, loggerLogger)
	defineCotaNftKvPairRepo := data.NewDefineCotaNftKvPairRepo(dataData, loggerLogger)
	defineCotaNftKvPairUsecase := biz.NewDefineCotaNftKvPairUsecase(defineCotaNftKvPairRepo, loggerLogger)
	holdCotaNftKvPairRepo := data.NewHoldCotaNftKvPairRepo(dataData, loggerLogger)
	holdCotaNftKvPairUsecase := biz.NewHoldCotaNftKvPairUsecase(holdCotaNftKvPairRepo, loggerLogger)
	registerCotaKvPairRepo := data.NewRegisterCotaKvPairRepo(dataData, loggerLogger)
	registerCotaKvPairUsecase := biz.NewRegisterCotaKvPairUsecase(registerCotaKvPairRepo, loggerLogger)
	withdrawCotaNftKvPairRepo := data.NewWithdrawCotaNftKvPairRepo(dataData, loggerLogger)
	withdrawCotaNftKvPairUsecase := biz.NewWithdrawCotaNftKvPairUsecase(withdrawCotaNftKvPairRepo, loggerLogger)
	blockParser := data.NewBlockParser(claimedCotaNftKvPairUsecase, defineCotaNftKvPairUsecase, holdCotaNftKvPairUsecase, registerCotaKvPairUsecase, withdrawCotaNftKvPairUsecase)
	syncService := service.NewSyncService(checkInfoUsecase, syncKvPairUsecase, loggerLogger, ckbNodeClient, systemScripts, blockParser)
	dbMigration := data.NewDBMigration(dataData, loggerLogger)
	appApp := newApp(loggerLogger, syncService, dbMigration)
	return appApp, func() {
		cleanup()
	}, nil
}
