CREATE TABLE IF NOT EXISTS issuer_info_versions (
    id bigint NOT NULL AUTO_INCREMENT,
    old_block_number bigint unsigned NOT NULL,
    block_number bigint unsigned NOT NULL,
    lock_hash char(64) NOT NULL,
    old_version varchar(40) NOT NULL,
    version varchar(40) NOT NULL,
    old_name varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    old_avatar varchar(500) NOT NULL,
    avatar varchar(500) NOT NULL,
    old_description varchar(1000) NOT NULL,
    description varchar(1000) NOT NULL,
    old_localization varchar(1000) NOT NULL,
    localization varchar(1000) NOT NULL,
    action_type tinyint unsigned NOT NULL,
    tx_index int unsigned NOT NULL,
    created_at datetime(6) NOT NULL,
    updated_at datetime(6) NOT NULL,
    PRIMARY KEY (id),
    KEY index_issuer_versions_on_block_number (block_number, action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
