CREATE TABLE IF NOT EXISTS class_infos (
    id bigint NOT NULL AUTO_INCREMENT,
    old_block_number bigint unsigned NOT NULL,
    block_number bigint unsigned NOT NULL,
    cota_id char(40) NOT NULL,
    old_version varchar(40) NOT NULL,
    version varchar(40) NOT NULL,
    old_name varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    old_symbol varchar(255) NOT NULL,
    symbol varchar(255) NOT NULL,
    old_description varchar(1000) NOT NULL,
    description varchar(1000) NOT NULL,
    old_image varchar(500) NOT NULL,
    image varchar(500) NOT NULL,
    old_audio varchar(500) NOT NULL,
    audio varchar(500) NOT NULL,
    old_video varchar(500) NOT NULL,
    video varchar(500) NOT NULL,
    old_model varchar(500) NOT NULL,
    model varchar(500) NOT NULL,
    old_schema varchar(1000) NOT NULL,
    `schema` varchar(1000) NOT NULL,
    old_properties varchar(1000) NOT NULL,
    properties varchar(1000) NOT NULL,
    old_localization varchar(1000) NOT NULL,
    localization varchar(1000) NOT NULL,
    action_type tinyint unsigned NOT NULL,
    tx_index int unsigned NOT NULL,
    created_at datetime(6) NOT NULL,
    updated_at datetime(6) NOT NULL,
    PRIMARY KEY (id),
    KEY index_class_versions_on_block_number (block_number, action_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
